export const LanguageCodesEnglishMappings = {
  'af': 'Afrikaans',
  'am': 'Amharic',
  'ar': 'Arabic',
  'ar-SA': 'Arabic (Saudi Arabia)',
  'ar-EG': 'Arabic (Egypt)',
  'ar-MA': 'Arabic (Morocco)',
  'ar-AE': 'Arabic (United Arab Emirates)',
  'az': 'Azerbaijani',
  'be': 'Belarusian',
  'bg': 'Bulgarian',
  'bn': 'Bengali',
  'bn-IN': 'Bengali (India)',
  'bn-BD': 'Bengali (Bangladesh)',
  'bs': 'Bosnian',
  'ca': 'Catalan',
  'cs': 'Czech',
  'cy': 'Welsh',
  'da': 'Danish',
  'de': 'German',
  'de-DE': 'German (Germany)',
  'de-AT': 'German (Austria)',
  'de-CH': 'German (Switzerland)',
  'el': 'Greek',
  'en': 'English',
  'en-US': 'English (United States)',
  'en-GB': 'English (United Kingdom)',
  'en-CA': 'English (Canada)',
  'en-AU': 'English (Australia)',
  'en-IN': 'English (India)',
  'en-NZ': 'English (New Zealand)',
  'en-ZA': 'English (South Africa)',
  'es': 'Spanish',
  'es-ES': 'Spanish (Spain)',
  'es-MX': 'Spanish (Mexico)',
  'es-AR': 'Spanish (Argentina)',
  'es-CL': 'Spanish (Chile)',
  'es-CO': 'Spanish (Colombia)',
  'es-PE': 'Spanish (Peru)',
  'es-US': 'Spanish (United States)',
  'et': 'Estonian',
  'eu': 'Basque',
  'fa': 'Persian',
  'fa-IR': 'Persian (Iran)',
  'fi': 'Finnish',
  'fil': 'Filipino',
  'fr': 'French',
  'fr-FR': 'French (France)',
  'fr-CA': 'French (Canada)',
  'fr-CH': 'French (Switzerland)',
  'fr-BE': 'French (Belgium)',
  'fr-LU': 'French (Luxembourg)',
  'ga': 'Irish',
  'gl': 'Galician',
  'gu': 'Gujarati',
  'he': 'Hebrew',
  'hi': 'Hindi',
  'hi-IN': 'Hindi (India)',
  'hr': 'Croatian',
  'hu': 'Hungarian',
  'hy': 'Armenian',
  'id': 'Indonesian',
  'is': 'Icelandic',
  'it': 'Italian',
  'it-IT': 'Italian (Italy)',
  'it-CH': 'Italian (Switzerland)',
  'ja': 'Japanese',
  'ja-JP': 'Japanese (Japan)',
  'jv': 'Javanese',
  'ka': 'Georgian',
  'kk': 'Kazakh',
  'km': 'Khmer',
  'kn': 'Kannada',
  'ko': 'Korean',
  'ko-KR': 'Korean (South Korea)',
  'ku': 'Kurdish',
  'ky': 'Kyrgyz',
  'lo': 'Lao',
  'lt': 'Lithuanian',
  'lv': 'Latvian',
  'mk': 'Macedonian',
  'ml': 'Malayalam',
  'mn': 'Mongolian',
  'mr': 'Marathi',
  'ms': 'Malay',
  'ms-MY': 'Malay (Malaysia)',
  'ms-SG': 'Malay (Singapore)',
  'my': 'Burmese',
  'ne': 'Nepali',
  'nl': 'Dutch',
  'nl-NL': 'Dutch (Netherlands)',
  'nl-BE': 'Dutch (Belgium)',
  'no': 'Norwegian',
  'nb': 'Norwegian Bokmål',
  'nn': 'Norwegian Nynorsk',
  'or': 'Odia',
  'pa': 'Punjabi',
  'pa-IN': 'Punjabi (India)',
  'pa-PK': 'Punjabi (Pakistan)',
  'pl': 'Polish',
  'pt': 'Portuguese',
  'pt-PT': 'Portuguese (Portugal)',
  'pt-BR': 'Portuguese (Brazil)',
  'ro': 'Romanian',
  'ro-RO': 'Romanian (Romania)',
  'ru': 'Russian',
  'ru-RU': 'Russian (Russia)',
  'si': 'Sinhala',
  'sk': 'Slovak',
  'sl': 'Slovenian',
  'so': 'Somali',
  'sq': 'Albanian',
  'sr': 'Serbian',
  'sr-RS': 'Serbian (Serbia)',
  'sv': 'Swedish',
  'sv-SE': 'Swedish (Sweden)',
  'sw': 'Swahili',
  'sw-KE': 'Swahili (Kenya)',
  'ta': 'Tamil',
  'ta-IN': 'Tamil (India)',
  'ta-LK': 'Tamil (Sri Lanka)',
  'te': 'Telugu',
  'th': 'Thai',
  'th-TH': 'Thai (Thailand)',
  'tr': 'Turkish',
  'tr-TR': 'Turkish (Turkey)',
  'uk': 'Ukrainian',
  'uk-UA': 'Ukrainian (Ukraine)',
  'ur': 'Urdu',
  'ur-PK': 'Urdu (Pakistan)',
  'ur-IN': 'Urdu (India)',
  'uz': 'Uzbek',
  'vi': 'Vietnamese',
  'vi-VN': 'Vietnamese (Vietnam)',
  'xh': 'Xhosa',
  'yo': 'Yoruba',
  'zh': 'Chinese',
  'zh-CN': 'Chinese (Simplified, China)',
  'zh-SG': 'Chinese (Simplified, Singapore)',
  'zh-HK': 'Chinese (Traditional, Hong Kong)',
  'zh-TW': 'Chinese (Traditional, Taiwan)',
  'zu': 'Zulu',
} as const;

export const LanguageCodes = [
  'af',
  'am',
  'ar',
  'ar-SA',
  'ar-EG',
  'ar-MA',
  'ar-AE',
  'az',
  'be',
  'bg',
  'bn',
  'bn-IN',
  'bn-BD',
  'bs',
  'ca',
  'cs',
  'cy',
  'da',
  'de',
  'de-DE',
  'de-AT',
  'de-CH',
  'el',
  'en',
  'en-US',
  'en-GB',
  'en-CA',
  'en-AU',
  'en-IN',
  'en-NZ',
  'en-ZA',
  'es',
  'es-ES',
  'es-MX',
  'es-AR',
  'es-CL',
  'es-CO',
  'es-PE',
  'es-US',
  'et',
  'eu',
  'fa',
  'fa-IR',
  'fi',
  'fil',
  'fr',
  'fr-FR',
  'fr-CA',
  'fr-CH',
  'fr-BE',
  'fr-LU',
  'ga',
  'gl',
  'gu',
  'he',
  'hi',
  'hi-IN',
  'hr',
  'hu',
  'hy',
  'id',
  'is',
  'it',
  'it-IT',
  'it-CH',
  'ja',
  'ja-JP',
  'jv',
  'ka',
  'kk',
  'km',
  'kn',
  'ko',
  'ko-KR',
  'ku',
  'ky',
  'lo',
  'lt',
  'lv',
  'mk',
  'ml',
  'mn',
  'mr',
  'ms',
  'ms-MY',
  'ms-SG',
  'my',
  'ne',
  'nl',
  'nl-NL',
  'nl-BE',
  'no',
  'nb',
  'nn',
  'or',
  'pa',
  'pa-IN',
  'pa-PK',
  'pl',
  'pt',
  'pt-PT',
  'pt-BR',
  'ro',
  'ro-RO',
  'ru',
  'ru-RU',
  'si',
  'sk',
  'sl',
  'so',
  'sq',
  'sr',
  'sr-RS',
  'sv',
  'sv-SE',
  'sw',
  'sw-KE',
  'ta',
  'ta-IN',
  'ta-LK',
  'te',
  'th',
  'th-TH',
  'tr',
  'tr-TR',
  'uk',
  'uk-UA',
  'ur',
  'ur-PK',
  'ur-IN',
  'uz',
  'vi',
  'vi-VN',
  'xh',
  'yo',
  'zh',
  'zh-CN',
  'zh-SG',
  'zh-HK',
  'zh-TW',
  'zu',
] as const;

export type LanguageCode = keyof typeof LanguageCodesEnglishMappings;
